### Get all courses
GET http://localhost:8000/api/courses

### Get one course
GET http://localhost:8000/api/courses/6a7e8c360efce5962977e1fe

### Filter courses by status
GET http://localhost:8000/api/courses?status=ACTIVE

### Filter courses by category
GET http://localhost:8000/api/courses?category=Software Engineering

### Filter courses by level
GET http://localhost:8000/api/courses?level=Beginner

### Filter courses by capacity
GET http://localhost:8000/api/courses?capacity=FULL

### Get Paged courses
GET http://localhost:8000/api/courses/paged?page=0&size=5

### Get Paged courses sorted by name ascending
GET http://localhost:8000/api/courses/paged?page=0&size=5&sortBy=title&direction=asc

### Get Paged courses sorted by courseCode descending
GET http://localhost:8000/api/courses/paged?page=0&size=5&sortBy=courseCode&direction=desc

### Get invalid course
GET http://localhost:8000/api/courses/999

### Create a new course
POST http://localhost:8000/api/courses
Content-Type: application/json

{
    "courseCode": "CS104",
    "title": "Introduction to Computer Science",
    "description": "An introductory course on computer science concepts.",
    "category": "Computer Science",
    "level" : "Beginner"
    "maxCapacity": "3 Empty"
}

### Create invalid new course
POST http://localhost:8000/api/courses
Content-Type: application/json

{
    "courseCode": "",
    "title": "",
    "description": "",
    "category": "",
    "maxCapacity": 0
}

### Check wrong course ###

### Filter courses by status
GET http://localhost:8000/api/courses?status=INVALID

### Get Paged courses
GET http://localhost:8000/api/courses/paged?page=0&size=100

### Get Paged courses sorted by name ascending
GET http://localhost:8000/api/courses/paged?page=0&size=5&sortBy=unknownDirection&direction=asc

### Get Paged courses
GET http://localhost:8000/api/courses?status=ACTIVE&level=ADVANCED

