@baseUrl = http://localhost:8000
@studentToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXNvbi5sZWVAZXhhbXBsZS5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlzcyI6ImNvdXJzZS1lbnJvbG1lbnQtYXBpIiwibmFtZSI6Ikphc29uIExlZSIsImV4cCI6MTc4NzMzNzQ4NSwiaWF0IjoxNzg3MzMzODg1LCJ1c2VySWQiOiI2YTg3MjUwYTA3N2I4YjBlMmYzZGUyYmUifQ.wYtkV68DnDFyObw9O9ElMGSsjHN97VG6eo5jgt7EFjw
@courseId = 6a7eea1a2ea649523eeb6a82
@enrolmentId= 6a8480d2fc21a148ac492936

### 1. Login normal student
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "student@example.com",
    "password": "Student@12345"
}

### 2. Enroll Student in a Course
POST {{baseUrl}}/api/v1/enrolments
Authorization: Bearer {{studentToken}}
Content-Type: application/json

{
  "courseId": "{{courseId}}"
}

### 3. Get My Enrolled Courses
GET {{baseUrl}}/api/v1/enrolments/my-courses
Authorization: Bearer {{studentToken}}

### 4. Drop My Enrolled Courses

PUT {{baseUrl}}/api/v1/enrolments/{{enrolmentId}}/drop
Authorization: Bearer {{studentToken}}